CREATE TRIGGER tipTrigger
AFTER INSERT ON Tip
FOR EACH ROW
WHEN (NEW.user_id IS NOT NULL)
EXECUTE PROCEDURE updateTipCount();

CREATE TRIGGER checkInTrigger
AFTER INSERT ON CheckIn
FOR EACH ROW
WHEN (NEW.business_id IS NOT NULL)
EXECUTE PROCEDURE updateCheckInCount();

CREATE TRIGGER likeTrigger
AFTER UPDATE OF likes ON Tip
FOR EACH ROW
WHEN (NEW.user_id IS NOT NULL)
EXECUTE PROCEDURE updateLikeCount();

CREATE TRIGGER likeTrigger2
AFTER INSERT ON Tip
FOR EACH ROW
WHEN (NEW.user_id IS NOT NULL)
EXECUTE PROCEDURE insertLikeCount();
